### ISSUE TITLE
Fp16 model runs slower than fp32 model

### ISSUE THREAD

**Issue by HemaSowjanyaMamidi** [microsoft/onnxconverter-common#169]
Hi @jcwchen,
I converted a model from keras to onnx and converted that float32 to float16 model using float16.py and noticed that the inference time it took was more than the float32 model on CPU. So can you please let me know the reason behind it?

Thanks

**Comment by jcwchen** [comment]
Hi @HemaSowjanyaMamidi,
I am not an expert about this, but I think basically using CPU won't gain speed improvement for using float16, at least for ONNXRuntime, because not every CPU operator has implementation for float 16. In that case, it will even need to convert it back to float32 which slows the speed. https://github.com/microsoft/onnxruntime/issues/5025

Other folks might have different opinions about this. Please correct me if I am wrong. Thank you.

**Comment by HemaSowjanyaMamidi** [comment]
Hi @jcwchen,
Are there any other ways to convert the model to int8 or int16 using this converter(similar to the float16.py).

**Comment by HemaSowjanyaMamidi** [comment]
And also can you explain the differences between quantizing models using QAT, PTQ, dynamic and using this converter method.

**Comment by jcwchen** [comment]
There is a related issue about this: https://github.com/onnx/onnx/issues/2846
As mentioned, you can check the document here to use quantization to convert your ONNX model to other data types. :https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/tools/quantization/README.md.

Quantization is doing the conversion in the runtime and it is more flexible (supports more data type). By contrast, float16 here only supports  converting from float32 to float16 and it can be done offline (directly modify the ONNX model).

Again, I am not familiar with this part so I might be wrong. Thanks.
