### ISSUE TITLE
regarding the keep_io_types in float16 converter

### ISSUE THREAD

**Issue by wangyems** [microsoft/onnxconverter-common#179]
https://github.com/microsoft/onnxconverter-common/blob/master/onnxconverter_common/float16.py#L135

I think it's better for us to move the keep_io_types logic to the bottom(after the major fp16 conversion is done) because in the current implementation, there are so many inputs in model.graph.input are float at the beginning. Then many cast nodes will be added for that.

Current use of convert_float_to_float16 with keep_io_types=True:
model_fp16_ = oc.convert_float_to_float16(model_fp32, keep_io_types=False)
model_fp16 = oc.convert_float_to_float16(model_fp16_, keep_io_types=True)

Ideally, just one call of convert_float_to_float16 should be able to do the conversion

**Comment by TomWildenhain-Microsoft** [comment]
You should not need to convert the model twice.  The conversion you are doing should actually be equivalent to **not** keeping IO types since the first conversion will change the IO types and the second will leave them changed.  If it is having a different effect, upload the model and I'll take a look.

As far as unnecessary CAST nodes go, the current conversion script does sometime add back-to-back casts (fp32->fp16->fp32).  ONNXRuntime will cancel these out before inference, so they shouldn't have any effect.  Still it would be nice to remove them.  I'll hopefully be able to update it in a bit.
